(Thu Nov 14 16:20:49 2019)(-0.121918 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/farmer/.local/lib/python3.7/site-packages/pyscannerbit/ScannerBit/lib/libscanner_diver_1.0.0.so".

Raised at: line 102 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-req-build-d6xcvmyb/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Thu Nov 14 16:20:49 2019)(-0.121896 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/farmer/.local/lib/python3.7/site-packages/pyscannerbit/ScannerBit/lib/libscanner_diver_1.0.2.so".

Raised at: line 102 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-req-build-d6xcvmyb/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Thu Nov 14 16:20:49 2019)(-0.110378 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/farmer/.local/lib/python3.7/site-packages/pyscannerbit/ScannerBit/lib/libscanner_great.so".

Raised at: line 102 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-req-build-d6xcvmyb/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Thu Nov 14 16:20:49 2019)(-0.0977666 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/farmer/.local/lib/python3.7/site-packages/pyscannerbit/ScannerBit/lib/libscanner_multinest_3.10.so".

Raised at: line 102 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-req-build-d6xcvmyb/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Thu Nov 14 16:20:49 2019)(0.0114146 [s])[Default,Utilities]:
Random number engine mt19937_64 (default) selected with seed 51977430.
--<>--<>--<>--<>--<>--<>--<>--
(Thu Nov 14 16:20:49 2019)(0.011934 [s])[Default,Printers][Info]:
Running shell command: rm -f pyscannerbit_run_data/twalk_scan/samples//results.hdf5
--<>--<>--<>--<>--<>--<>--<>--
(Thu Nov 14 16:20:49 2019)(0.0181291 [s])[Default,Core]:
Starting scan.
--<>--<>--<>--<>--<>--<>--<>--
(Thu Nov 14 16:20:49 2019)(0.0200182 [s])[Default,Printers][Info]:
Assigned printer ID '0' to output quantity with label 'LogLike'
--<>--<>--<>--<>--<>--<>--<>--
(Thu Nov 14 16:20:49 2019)(0.0201145 [s])[Default,Printers][Info]:
Assigned printer ID '1' to output quantity with label 'pointID'
--<>--<>--<>--<>--<>--<>--<>--
(Thu Nov 14 16:20:49 2019)(0.0201627 [s])[Default,Printers][Info]:
Assigned printer ID '2' to output quantity with label 'MPIrank'
--<>--<>--<>--<>--<>--<>--<>--
(Thu Nov 14 16:20:49 2019)(0.0219043 [s])[Default,Printers][Info]:
Assigned printer ID '3' to output quantity with label 'mult'
--<>--<>--<>--<>--<>--<>--<>--
(Thu Nov 14 16:20:49 2019)(0.0219609 [s])[Default,Printers][Info]:
Assigned printer ID '4' to output quantity with label 'chain'
--<>--<>--<>--<>--<>--<>--<>--
